version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/viplab-standalone-frontend-vue'
    schedule:
      interval: 'weekly'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
