# base image: latest 16er version, with 18, build breaks
FROM node:16.14.2-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# start app
ENTRYPOINT ["npm"]
EXPOSE 8081
