FROM node:18.18.2-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
#ENV UV_USE_IO_URING 0
# start app
ENTRYPOINT ["npm"]
EXPOSE 8081
