name: "Build and Release"

on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+'

jobs:
  build-and-save-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Checkout the branch that triggered the workflow.
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18'
      
      - name: npm install, build
        env: 
          NODE_OPTIONS: "--max_old_space_size=8000"
        run: |
          cd viplab-standalone-frontend-vue
          npm install
          npm run build

      - name: Archive dist
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'dist.zip'
          path: 'viplab-standalone-frontend-vue/dist'

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist.zip"
